name: Deploy Flutter Web to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # 🔥 IMPORTANT FIX (upgrade Flutter)
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.0"
          channel: stable

      - name: Clean project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release

      - name: Deploy to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@example.com"

          git clone https://user:$HF_TOKEN@huggingface.co/spaces/Anil1515/chess-frontend-static hf

          rm -rf hf/*
          cp -r build/web/* hf/

          cd hf
          git add .
          git commit -m "auto deploy" || echo "no changes"
          git push
